title: Language is a virus from outer space
description: Thoughts on data, language and information
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
